### PR TITLE
Use dvclive 'Live()' object. Update Requirements

### PR DESCRIPTION
**Pull request by da2ce7**
* Update required dvclive version to >=0.4.0.
* Only import 'Live' from dvclive package.
* Create and use instance of 'Live()' object.

https://dvc.org/doc/dvclive/api-reference/live/get_step

### CODE REVIEW

**Review by daavoo — CHANGES_REQUESTED** [review]
Hi @da2ce7 ! Thanks for catching this!

The updates look good. 

However, given that this repo is associated with a [blog post](https://dvc.org/blog/transfer-learning-experiments) whose content is not going to change (right? @shcheklein), I think it would be better to just pint the `dvclive` version (`dvclive<0.4.0`) on [requirements.txt](https://github.com/iterative/pretrained-model-demo/blob/main/requirements.txt) so that the code snippets in the blog post will match the code in this repo (while people still being able to install deps and run the repo)

**Comment by shcheklein** [comment]
@daavoo I don't have a strong opinion on updating the blogs post / vs library version. Both options work fine I think.

**Review by daavoo — CHANGES_REQUESTED** [review]
So a solution that won't require updating the blog post:

@da2ce7 If we replace import at the beginning:

```git
- import dvclive
+ from dvclive import Live
```

And then we just add this line before any of the calls:

```python
dvclive = Live()
```

We won't need to update any of the other lines and the code snippet in the blog post would match the repo.

I would still recommend pinning `dvclive` on requirements as part of the P.R. (but in this case would be `dvclive>=0.4.0`.

**Review by daavoo — APPROVED** [review]
🚀

**Pull request merged**
